#!/usr/bin/env python3
"""Generate this project's self-contained executables, pinned to uv.lock.

Both `bin/icemaint` and `bin/demo` come from here, so a dependency change
cannot leave one of them behind.

The output is a PEP 723 script: a single file with its dependency set inlined as
a comment header, run through `uv run --script`. uv builds and caches an
isolated environment for it on first run, so the executable never resolves
against a global site-packages and always uses exactly the third-party versions
in uv.lock.

`icemaint` itself is referenced as an *editable* path install. That is
deliberate. uv keys its script-environment cache on the inline metadata, so with
a plain (non-editable) path source the project is built into a wheel once and
every later run serves that cached wheel -- the executable silently keeps
running whatever the code looked like at first run, even after the source
changes and even after regenerating this file. Editable makes the checkout
authoritative, which is the right semantics for a tool run out of the repository
it maintains. To ship a frozen artifact instead, build a versioned wheel and pin
that.

Regenerate after any `uv lock` / `uv sync --upgrade`:

    uv run scripts/build-executable.py
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Assembled rather than written literally: uv scans this file for PEP 723
# metadata too, and a literal "# /// script" line here would be parsed as this
# generator's own (unterminated) header.
_OPEN = "# " + "/// script"
_CLOSE = "# " + "///"

TEMPLATE = """#!/usr/bin/env -S uv run --quiet --script
{open_tag}
# requires-python = "{python}"
# dependencies = [
{deps}
# ]
#
# [tool.uv.sources]
# icemaint = {{ path = "{project}", editable = true }}
{close_tag}
'''{name} -- generated by scripts/build-executable.py. Do not edit.

Pinned to uv.lock. Regenerate with `uv run scripts/build-executable.py`.
'''

import sys

from {module} import {function}

if __name__ == "__main__":
    sys.exit({function}())
"""

#: Every executable this project ships. Both are generated from the same lock,
#: so a dependency change cannot leave one of them behind.
ENTRY_POINTS = {
    "icemaint": "icemaint.cli:main",
    "demo": "himsdemo.cli:main",
}


def locked_requirements() -> list[str]:
    """Exact pins for the runtime dependency set, from uv.lock.

    All extras are included. A CLI that cannot reach S3, cannot open a local
    warehouse, and cannot write a bucket-partitioned table is not a usable
    executable, and the extras are small next to pyarrow.
    """
    out = subprocess.run(
        [
            "uv",
            "export",
            "--all-extras",
            "--no-dev",
            "--no-emit-project",
            "--no-hashes",
            "--no-annotate",
            "--format",
            "requirements.txt",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout

    pins = []
    for line in out.splitlines():
        line = line.strip()
        if not line or line.startswith(("#", "-")):
            continue
        pins.append(line)
    return sorted(pins)


def requires_python() -> str:
    """Pin the executable to the interpreter the project is tested on.

    Without this, uv resolves `>=3.11` to the newest interpreter it can find --
    so the shipped executable could run on a Python the test suite never
    touched. `.python-version` is the same file `uv sync` uses for .venv, so the
    two stay in step.
    """
    pin = ROOT / ".python-version"
    if pin.exists() and (version := pin.read_text().strip()):
        return f"=={version}.*"

    text = (ROOT / "pyproject.toml").read_text()
    match = re.search(r'requires-python\s*=\s*"([^"]+)"', text)
    if not match:
        raise SystemExit("could not read requires-python from pyproject.toml")
    return match.group(1)


def render(project_path: str | Path, name: str, entry_point: str) -> str:
    # Extras go on the requirement, not on [tool.uv.sources], which has no
    # `extras` key.
    deps = "\n".join(
        f'#     "{pin}",' for pin in ["icemaint[s3,bucket,sql]", *locked_requirements()]
    )
    module, _, function = entry_point.partition(":")
    return TEMPLATE.format(
        open_tag=_OPEN,
        close_tag=_CLOSE,
        python=requires_python(),
        deps=deps,
        project=project_path,
        name=name,
        module=module,
        function=function,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--only",
        choices=sorted(ENTRY_POINTS),
        help="generate just one executable instead of all of them",
    )
    parser.add_argument("--bin-dir", type=Path, default=ROOT / "bin")
    parser.add_argument(
        "--project-path",
        default="..",
        help="path recorded as the icemaint source. Relative by default (the "
        "executables live one level below the project root) so the checked-in "
        "artifacts work in anyone's clone; uv resolves it against the script's "
        "own directory, not the caller's cwd. Pass an absolute path to pin one "
        "checkout.",
    )
    args = parser.parse_args()

    names = [args.only] if args.only else sorted(ENTRY_POINTS)
    args.bin_dir.mkdir(parents=True, exist_ok=True)
    for name in names:
        out = args.bin_dir / name
        out.write_text(render(args.project_path, name, ENTRY_POINTS[name]))
        out.chmod(0o755)
        print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
